version: "3.3"

services:
  app:
    container_name: react-client
    image: react-client
    build: 
      context: .
      target: development
    volumes: 
      - ./src:/app/src
    ports:
      - 3000:3000